- hosts: localhost
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
  tasks:
    - import_tasks: tasks/ranger.yml
    - import_tasks: tasks/zig.yml
