- name: Update apt package index
  apt:
    update_cache: yes
  become: true

- name: Install Python3 and pip3
  apt:
    name:
      - python3
      - python3-pip
    state: present
  become: true

- name: Install Ranger using pip3
  pip:
    name: ranger-fm
    executable: pip3
  become: true
